[package]
name = "benson-primitives"
version = "1.0.0"
authors = ["Annie Lai <ng8eke@163.com>"]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc1" }
sr-primitives = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc1" }
support = { package = "srml-support", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc1" }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc1" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"primitives/std",
	"sr-primitives/std",
	"support/std",
]
