[package]
name = "benson-primitives"
version = "1.0.0"
authors = ["Annie Lai <ng8eke@163.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc2" }
sp-core = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc2" }
sp-runtime = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "1.0.0-rc2" }

[dev-dependencies]
pretty_assertions = "0.6.1"
sp-serializer = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }


[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
]
